In [1]:
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`



SyntaxError: invalid syntax (2654050845.py, line 3)

#### 1. Import the numpy package under the name `np` (★☆☆)


In [5]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [12]:
a = np.zeros(10)

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [15]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [16]:
a = np.arange(0, 9).reshape((3,3))
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [22]:
arr = np.array([1,2,0,0,4,0])
a = arr[np.nonzero(arr)]
a

array([1, 2, 4])

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [25]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [26]:
b = np.random.random((3,3,3))
print(b)

[[[0.17564972 0.43427063 0.29932642]
  [0.39289617 0.35637262 0.39862707]
  [0.52322456 0.51774695 0.51167672]]

 [[0.17801699 0.96468366 0.06172159]
  [0.11593661 0.56025292 0.97545092]
  [0.48309101 0.48672309 0.57485102]]

 [[0.22347289 0.96774834 0.12531167]
  [0.96067868 0.45383493 0.29625281]
  [0.37839825 0.03419087 0.05664687]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [33]:
a = np.random.random((10,10))
print(a.min())
print(a.max())

0.021371101874648968
0.9957812280482948


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [36]:
b = np.random.random((30))
np.mean(b)

0.44978568813059705

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [59]:
arr = np.array([0,1,2,3,4])
arr2 = np.diag(arr)
print(arr2)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [63]:
a = np.eye(5)
array = a - np.mean(a)/np.std(a)
array

array([[ 0.5, -0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5,  0.5]])


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [64]:
a = [1,2,4,6,10,11]
b = [3,6,8,9,0,2,1,7]
np.intersect1d(a,b)

array([1, 2, 6])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [67]:
b = np.random.random((10))
np.sort(b)

array([0.03769988, 0.0673955 , 0.14893213, 0.23820042, 0.63684878,
       0.64104276, 0.66727429, 0.71281817, 0.75570732, 0.94561391])


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [92]:
xMatrix = np.random.random((10))
maxNum = np.amax(xMatrix, axis=1)
xMatrix[xMatrix == max_num[:, None]] = 0

AxisError: axis 1 is out of bounds for array of dimension 1

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [ ]:
b = np.random.random((10))
mean(axis = 1, keepdims=)